export type ModeT = 'dark' | 'light';

export type ColorT =
  | 'red'
  | 'rose'
  | 'orange'
  | 'green'
  | 'blue'
  | 'yellow'
  | 'violet'
  | 'zinc'
  | 'slate'
  | 'stone'
  | 'gray'
  | 'neutral';

export type ThemeT =
  | 'red-dark'
  | 'rose-light'
  | 'rose-dark'
  | 'orange-light'
  | 'orange-dark'
  | 'green-light'
  | 'green-dark'
  | 'blue-light'
  | 'blue-dark'
  | 'yellow-light'
  | 'yellow-dark'
  | 'violet-light'
  | 'violet-dark'
  | 'zinc-light'
  | 'zinc-dark'
  | 'slate-light'
  | 'slate-dark'
  | 'stone-light'
  | 'stone-dark'
  | 'gray-light'
  | 'gray-dark'
  | 'neutral-light'
  | 'neutral-dark';
